[theme]
primaryColor = "#2a9d8f"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "Helvetica"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false